/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaafs;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author junjun
 */
public class AcadLeadViewLecturerList extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AcadLeadViewLecturerList.class.getName());

    protected List<String[]> userArray;
    protected List<String[]> relationship;
    protected List<String[]> modules;
    Functions func = new Functions();
    
    public String UserID = "";
    public String Role = "";

public AcadLeadViewLecturerList(String userid) {
    userArray = func.readCSV("users.txt");
    relationship = func.readCSV("leaderLecturerRelationship.txt");
    modules = func.readCSV("modules.txt");
    initComponents();
    this.UserID = userid;        
    loadUserData(userid);
    loadLecturerToTable();
    }

private void loadUserData(String userid) {
    if (userArray == null || userArray.isEmpty()) 
        return;

    for (int i = 0; i < userArray.size(); i++) {
        String[] user = userArray.get(i);
        if (user[0].equalsIgnoreCase(userid)) {
            AcadLeadName.setText(user[3]);
            userRole.setText(user[2]);
            Role = user[2];
            break;
            }
        }
    }

private void loadLecturerToTable() {
    DefaultTableModel model = (DefaultTableModel) lecturerlisttable.getModel();
    model.setRowCount(0);

// read from leaderLecturerRelationship.txt
    for (int i = 1; i < relationship.size(); i++) {
        String[] row = relationship.get(i);
        if (row.length < 2) continue;
        String leaderID = row[0];
        String lecturerID = row[1];
        String moduleID = "";
            if (row.length >= 3) {
                moduleID = row[2];
            }
        
// load from users.txt
        if (!leaderID.equalsIgnoreCase(UserID)) continue; 
        String lecturerName = "";
        for (int j = 1; j < userArray.size(); j++) {
            String[] user = userArray.get(j);
            if (user[0].equalsIgnoreCase(lecturerID)) {
                lecturerName = user[3]; 
                break;
                }
            }
        
        String moduleName = "";
        for (int k = 1; k < modules.size(); k++) {
            String[] module = modules.get(k);
            if (module[0].equalsIgnoreCase(moduleID)) {
                moduleName = module[1]; 
                break;
                }
            }
        
            model.addRow(new Object[]{lecturerID, lecturerName, moduleID, moduleName});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backbtn = new javax.swing.JButton();
        assignlecturerlbl = new javax.swing.JLabel();
        AcadLeadName = new javax.swing.JLabel();
        userRole = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lecturerlisttable = new javax.swing.JTable();
        assignmodulesbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backbtn.setText("BACK");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        assignlecturerlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        assignlecturerlbl.setText("LECTURER LIST");

        AcadLeadName.setText("jLabel1");

        userRole.setText("jLabel2");

        lecturerlisttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Lecturer ID", "Lecturer Name", "Module ID", "Module Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(lecturerlisttable);

        assignmodulesbtn.setText("ASSIGN MODULES");
        assignmodulesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmodulesbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(assignmodulesbtn)
                .addGap(93, 93, 93)
                .addComponent(backbtn)
                .addGap(167, 167, 167))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(assignlecturerlbl)
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(userRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AcadLeadName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AcadLeadName)
                        .addGap(18, 18, 18)
                        .addComponent(userRole))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(assignlecturerlbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backbtn)
                    .addComponent(assignmodulesbtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        AcadLeaderMenu acadleadermenu = new AcadLeaderMenu(UserID);
        acadleadermenu.setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_backbtnActionPerformed

    private void assignmodulesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmodulesbtnActionPerformed
        AcadLeadAssignModules acadleadassignmodules = new AcadLeadAssignModules(UserID);
        acadleadassignmodules.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_assignmodulesbtnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new AcadLeadViewLecturerList().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AcadLeadName;
    private javax.swing.JLabel assignlecturerlbl;
    private javax.swing.JButton assignmodulesbtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lecturerlisttable;
    private javax.swing.JLabel userRole;
    // End of variables declaration//GEN-END:variables
}
