/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaafs;
import java.util.List;

/**
 *
 * @author zhenz
 */
public class LecturerChangePassword extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LecturerChangePassword.class.getName());

    protected List<String[]> userArray;
    UserFunctions func = new UserFunctions();

    public String Role = "";
    public String UserID = "";
    
    private boolean passwordShow = false;
    
    public LecturerChangePassword() {
        userArray = func.readCSV("users.txt");
        initComponents();
    }
    
    public LecturerChangePassword(String UserID) {
        this();               
        this.UserID = UserID; 
        loadUserData(UserID); 
    }

    
    private void loadUserData(String userid) {
    if (userArray == null || userArray.isEmpty()) 
        return;

    for (int i = 0; i < userArray.size(); i++) {
        String[] user = userArray.get(i);
        if (user[0].equalsIgnoreCase(userid)) {
            lecturerName.setText(user[3]);
            userRole.setText(user[2]);
            break;
        }
    }
}
private void changePassword() {
    String oldPassword = new String(oldpasswordtxt.getPassword());
        String newPassword = new String(newpasswordtxt.getPassword());
        String confirmPassword = new String(confirmpasswordtxt.getPassword());
        
        if (oldPassword.equals("")) {
            statustxt.setText("Old Password cannot be empty.");
            return;
        }
        
        if (newPassword.equals("")) {
            statustxt.setText("New Password cannot be empty.");
            return;
        }
        
        if (confirmPassword.equals("")) {
            statustxt.setText("Confirm Password cannot be empty.");
            return;
       }
        
        boolean validOld = func.authUser(userArray, UserID, oldPassword);

        if (!validOld) {
            statustxt.setText("Old password is incorrect!");
            return;
        }
        
        if (!newPassword.equals(confirmPassword)) {
            statustxt.setText("New password do not match!");
            return;
        }
        
        boolean updated = func.updatePassword(userArray, UserID, newPassword);
    
        if (updated) {
            func.savePassword(userArray, "users.txt");
            statustxt.setText("Password changed successfully!");
            
            oldpasswordtxt.setText("");
            newpasswordtxt.setText("");
            confirmpasswordtxt.setText("");
        } 
        else {
            statustxt.setText("Password change failed.");
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profilePage = new javax.swing.JButton();
        designAsgmnt = new javax.swing.JButton();
        resultAsgmnt = new javax.swing.JButton();
        viewFeedback = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pageTitle = new javax.swing.JLabel();
        logOut = new javax.swing.JButton();
        lecturerName = new javax.swing.JLabel();
        userRole = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        changepasswordlbl = new javax.swing.JLabel();
        oldpasswordlbl = new javax.swing.JLabel();
        newpasswordlbl = new javax.swing.JLabel();
        confirmpasswordlbl = new javax.swing.JLabel();
        confirmbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        statuslbl = new javax.swing.JLabel();
        statustxt = new javax.swing.JTextField();
        confirmpasswordtxt = new javax.swing.JPasswordField();
        newpasswordtxt = new javax.swing.JPasswordField();
        oldpasswordtxt = new javax.swing.JPasswordField();
        showpassword1 = new javax.swing.JButton();
        showpassword2 = new javax.swing.JButton();
        showpassword3 = new javax.swing.JButton();
        profilePage1 = new javax.swing.JButton();
        designAsgmnt1 = new javax.swing.JButton();
        resultAsgmnt1 = new javax.swing.JButton();
        viewFeedback1 = new javax.swing.JButton();

        profilePage.setText("Profile");
        profilePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilePageActionPerformed(evt);
            }
        });

        designAsgmnt.setText("Design Assessment");
        designAsgmnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designAsgmntActionPerformed(evt);
            }
        });

        resultAsgmnt.setText("Assessment Results");
        resultAsgmnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultAsgmntActionPerformed(evt);
            }
        });

        viewFeedback.setText("View Feedback");
        viewFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFeedbackActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        pageTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        pageTitle.setText("STUDENT MAIN MENU");

        logOut.setText("Log Out");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        lecturerName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lecturerName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lecturerName.setText("yourName");

        userRole.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userRole.setText("yourRole");

        changepasswordlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        changepasswordlbl.setText("Change Password");

        oldpasswordlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        oldpasswordlbl.setText("Old Password");

        newpasswordlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newpasswordlbl.setText("New Password");

        confirmpasswordlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        confirmpasswordlbl.setText("Confirm Password");

        confirmbtn.setText("CONFIRM");
        confirmbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmbtnActionPerformed(evt);
            }
        });

        backbtn.setText("BACK");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        statuslbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        statuslbl.setText("Status");

        statustxt.setEditable(false);
        statustxt.setBorder(null);

        oldpasswordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldpasswordtxtActionPerformed(evt);
            }
        });

        showpassword1.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        showpassword1.setText("Show Password");
        showpassword1.setBorder(null);
        showpassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassword1ActionPerformed(evt);
            }
        });

        showpassword2.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        showpassword2.setText("Show Password");
        showpassword2.setBorder(null);
        showpassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassword2ActionPerformed(evt);
            }
        });

        showpassword3.setFont(new java.awt.Font("Segoe UI", 0, 6)); // NOI18N
        showpassword3.setText("Show Password");
        showpassword3.setBorder(null);
        showpassword3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassword3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(confirmbtn)
                .addGap(18, 18, 18)
                .addComponent(backbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(changepasswordlbl)
                .addGap(122, 122, 122))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oldpasswordlbl)
                    .addComponent(newpasswordlbl)
                    .addComponent(confirmpasswordlbl)
                    .addComponent(statuslbl))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(statustxt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(confirmpasswordtxt)
                                    .addComponent(newpasswordtxt)
                                    .addComponent(oldpasswordtxt))
                                .addGap(65, 65, 65))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(showpassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(showpassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(showpassword3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(changepasswordlbl)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldpasswordlbl)
                    .addComponent(oldpasswordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showpassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newpasswordlbl)
                    .addComponent(newpasswordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(showpassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmpasswordlbl)
                    .addComponent(confirmpasswordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(showpassword3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statuslbl)
                    .addComponent(statustxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmbtn)
                    .addComponent(backbtn))
                .addGap(26, 26, 26))
        );

        profilePage1.setText("Profile");
        profilePage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilePage1ActionPerformed(evt);
            }
        });

        designAsgmnt1.setText("Design Assessment");
        designAsgmnt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designAsgmnt1ActionPerformed(evt);
            }
        });

        resultAsgmnt1.setText("Assessment Results");
        resultAsgmnt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultAsgmnt1ActionPerformed(evt);
            }
        });

        viewFeedback1.setText("View Feedback");
        viewFeedback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFeedback1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pageTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 331, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lecturerName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userRole, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(profilePage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(designAsgmnt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resultAsgmnt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewFeedback1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lecturerName)
                        .addGap(1, 1, 1)
                        .addComponent(userRole))
                    .addComponent(pageTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(profilePage1)
                        .addGap(18, 18, 18)
                        .addComponent(designAsgmnt1)
                        .addGap(25, 25, 25)
                        .addComponent(resultAsgmnt1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(viewFeedback1)
                        .addGap(175, 175, 175)
                        .addComponent(logOut))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed

        func.logout(this, UserID);

    }//GEN-LAST:event_logOutActionPerformed

    private void confirmbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmbtnActionPerformed
        changePassword();
    }//GEN-LAST:event_confirmbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        LecturerProfilePage studProf = new LecturerProfilePage(UserID);
        this.setVisible(false);
        studProf.setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    private void oldpasswordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldpasswordtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldpasswordtxtActionPerformed

    private void showpassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassword1ActionPerformed

        if (!passwordShow){
            oldpasswordtxt.setEchoChar((char) 0);
            showpassword1.setText("Hide Password");
            passwordShow = true;
        }
        else {
            oldpasswordtxt.setEchoChar('•');
            showpassword1.setText("Show Password");
            passwordShow = false;
        }
    }//GEN-LAST:event_showpassword1ActionPerformed

    private void showpassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassword2ActionPerformed
        if (!passwordShow){
            newpasswordtxt.setEchoChar((char) 0);
            showpassword2.setText("Hide Password");
            passwordShow = true;
        }
        else {
            newpasswordtxt.setEchoChar('•');
            showpassword2.setText("Show Password");
            passwordShow = false;
        }
    }//GEN-LAST:event_showpassword2ActionPerformed

    private void showpassword3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassword3ActionPerformed
        if (!passwordShow){
            confirmpasswordtxt.setEchoChar((char) 0);
            showpassword3.setText("Hide Password");
            passwordShow = true;
        }
        else {
            confirmpasswordtxt.setEchoChar('•');
            showpassword3.setText("Show Password");
            passwordShow = false;
        }
    }//GEN-LAST:event_showpassword3ActionPerformed

    private void profilePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilePageActionPerformed
        LecturerProfilePage StuProfile = new LecturerProfilePage(UserID);
        this.setVisible(false);
        StuProfile.setVisible(true);
    }//GEN-LAST:event_profilePageActionPerformed

    private void designAsgmntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_designAsgmntActionPerformed
        LecturerDesign lectProfile = new LecturerDesign(UserID);
        this.setVisible(false);
        lectProfile.setVisible(true);
    }//GEN-LAST:event_designAsgmntActionPerformed

    private void resultAsgmntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultAsgmntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultAsgmntActionPerformed

    private void viewFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFeedbackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewFeedbackActionPerformed

    private void profilePage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilePage1ActionPerformed
        LecturerProfilePage StuProfile = new LecturerProfilePage(UserID);
        this.setVisible(false);
        StuProfile.setVisible(true);
    }//GEN-LAST:event_profilePage1ActionPerformed

    private void designAsgmnt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_designAsgmnt1ActionPerformed
        LecturerDesign lectProfile = new LecturerDesign(UserID);
        this.setVisible(false);
        lectProfile.setVisible(true);
    }//GEN-LAST:event_designAsgmnt1ActionPerformed

    private void resultAsgmnt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultAsgmnt1ActionPerformed
        LecturerResultsList viewResults = new LecturerResultsList(UserID);
        this.setVisible(false);
        viewResults.setVisible(true);
    }//GEN-LAST:event_resultAsgmnt1ActionPerformed

    private void viewFeedback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFeedback1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewFeedback1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LecturerChangePassword().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel changepasswordlbl;
    private javax.swing.JButton confirmbtn;
    private javax.swing.JLabel confirmpasswordlbl;
    private javax.swing.JPasswordField confirmpasswordtxt;
    private javax.swing.JButton designAsgmnt;
    private javax.swing.JButton designAsgmnt1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lecturerName;
    private javax.swing.JButton logOut;
    private javax.swing.JLabel newpasswordlbl;
    private javax.swing.JPasswordField newpasswordtxt;
    private javax.swing.JLabel oldpasswordlbl;
    private javax.swing.JPasswordField oldpasswordtxt;
    private javax.swing.JLabel pageTitle;
    private javax.swing.JButton profilePage;
    private javax.swing.JButton profilePage1;
    private javax.swing.JButton resultAsgmnt;
    private javax.swing.JButton resultAsgmnt1;
    private javax.swing.JButton showpassword1;
    private javax.swing.JButton showpassword2;
    private javax.swing.JButton showpassword3;
    private javax.swing.JLabel statuslbl;
    private javax.swing.JTextField statustxt;
    private javax.swing.JLabel userRole;
    private javax.swing.JButton viewFeedback;
    private javax.swing.JButton viewFeedback1;
    // End of variables declaration//GEN-END:variables
}
