/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaafs;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author junjun
 */
public class LecturerReport extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LecturerReport.class.getName());

    protected List<String[]> userArray;
    protected List<String[]> modules;
    protected List<String[]> feedbacks;
    protected List<String[]> assessments;
    
    UserFunctions func = new UserFunctions();

    public String Role = "";
    public String UserID = "";
    private String academicLeaderID;
    public String Name = "";
    public String Assessment = "";
    public String Feedback = "";
    public String Rating = "";
        
    public LecturerReport() {
        userArray = func.readCSV("users.txt");
        modules = func.readCSV("modules.txt");
        feedbacks = func.readCSV("studentFeedback.txt");
        assessments = func.readCSV("assessmentquestion.txt");
        initComponents();
    }
    
    public LecturerReport(String lecturerID, String academicLeaderID) {
        this();               
        this.UserID = lecturerID; 
        this.academicLeaderID = academicLeaderID;
        loadUserData(lecturerID); 
        getFeedbackCount(lecturerID);
        calculateAverageRating(lecturerID);
    }

    
    private void loadUserData(String userid) {
        if (userArray == null || userArray.isEmpty()) 
            return;

        for (int i = 0; i < userArray.size(); i++) {
            String[] user = userArray.get(i);
            if (user[0].equalsIgnoreCase(userid)) {
                lectureridtxt.setText(user[3]);
                lecturernametxt.setText(user[0]);
                break;
            }
        }
        
        int totalfeedback = getFeedbackCount(userid);
        numberfeedbacktxt.setText(String.valueOf(totalfeedback));

        int totalAssessments = calculateAssessment(userid);
        assessmentnumtxt.setText(String.valueOf(totalAssessments));

    }

    private int getFeedbackCount(String lecturerID) {
        if (lecturerID == null || lecturerID.isEmpty())
            return 0;

        int count = 0;
        for (int i = 1; i < feedbacks.size(); i++) {  
            String[] feedback = feedbacks.get(i);
            if (feedback[2].equalsIgnoreCase(lecturerID)) {
                count++;
            }
        }

        return count;
    } 
    
    private void calculateAverageRating(String lecturerID) {
        int totalrating = 0;
        int studentcount = 0;

        for (int i = 1; i < feedbacks.size(); i++) { // start from 1 to skip header
            String[] feedback = feedbacks.get(i);

            if (feedback[2].equalsIgnoreCase(lecturerID)) {
                try {
                    int rating = Integer.parseInt(feedback[5].trim()); // correct column for rating
                    totalrating += rating;
                    studentcount++;
                } catch (NumberFormatException e) {
                    System.out.println("Invalid rating value: " + feedback[5]);
                }
            }
        }

        if (studentcount > 0) {
            double avgrating = (double) totalrating / studentcount;
            ratingtxt.setText(String.format("%.2f / 5.00", avgrating));
        } else {
            ratingtxt.setText("0 / 5.00");
        }
    }

    
    private int calculateAssessment(String lecturerID) {
        if (lecturerID == null || lecturerID.isEmpty())
            return 0;
        
        List<String> lecturerModules = new ArrayList<>();

        for (int i = 1; i < modules.size(); i++) {  
            String[] module = modules.get(i);
            if (module.length > 2 && module[2].equalsIgnoreCase(lecturerID)) {  
                lecturerModules.add(module[0]);           
            }
        }

        int count = 0;
        for (int i = 1; i < assessments.size(); i++) {  
            String[] assessment = assessments.get(i);
            if (assessment.length > 1 && lecturerModules.contains(assessment[1])) {      
                count++;
            }
        }
        return count;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lecturerreportlbl = new javax.swing.JLabel();
        lectureridlbl = new javax.swing.JLabel();
        lecturernamelbl = new javax.swing.JLabel();
        lectureridtxt = new javax.swing.JTextField();
        lecturernametxt = new javax.swing.JTextField();
        ratinglbl = new javax.swing.JLabel();
        ratingtxt = new javax.swing.JTextField();
        assessmentnumlbl = new javax.swing.JLabel();
        assessmentnumtxt = new javax.swing.JTextField();
        backbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        numberfeedbacktxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lecturerreportlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lecturerreportlbl.setText("LECTURER REPORT");

        lectureridlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lectureridlbl.setText("Lecturer ID");

        lecturernamelbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lecturernamelbl.setText("Lecturer Name");

        lectureridtxt.setEditable(false);

        lecturernametxt.setEditable(false);
        lecturernametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturernametxtActionPerformed(evt);
            }
        });

        ratinglbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ratinglbl.setText("Rating");

        ratingtxt.setEditable(false);

        assessmentnumlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        assessmentnumlbl.setText("Assessment Created");

        assessmentnumtxt.setEditable(false);

        backbtn.setText("BACK");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Number of Feedback ");

        numberfeedbacktxt.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(ratinglbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberfeedbacktxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ratingtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(147, 147, 147))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lectureridlbl)
                            .addComponent(assessmentnumlbl)
                            .addComponent(lecturernamelbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lecturernametxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(assessmentnumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lectureridtxt, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(43, 43, 43))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lecturerreportlbl)
                .addGap(99, 99, 99)
                .addComponent(backbtn)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lecturerreportlbl)
                    .addComponent(backbtn))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lectureridlbl)
                    .addComponent(lectureridtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lecturernamelbl)
                    .addComponent(lecturernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assessmentnumlbl)
                    .addComponent(assessmentnumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(numberfeedbacktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ratingtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ratinglbl))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        AcadLeadReport acadleadreport = new AcadLeadReport(academicLeaderID);
        this.setVisible(false);
        acadleadreport.setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    private void lecturernametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturernametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lecturernametxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LecturerReport().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assessmentnumlbl;
    private javax.swing.JTextField assessmentnumtxt;
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lectureridlbl;
    private javax.swing.JTextField lectureridtxt;
    private javax.swing.JLabel lecturernamelbl;
    private javax.swing.JTextField lecturernametxt;
    private javax.swing.JLabel lecturerreportlbl;
    private javax.swing.JTextField numberfeedbacktxt;
    private javax.swing.JLabel ratinglbl;
    private javax.swing.JTextField ratingtxt;
    // End of variables declaration//GEN-END:variables
}
