/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaafs;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author junjun
 */
public class ModulesReport extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ModuleReport.class.getName());

    protected List<String[]> modules;    
    protected List<String[]> assessmentResult;

    private UserFunctions func = new UserFunctions();
    
    private String moduleID;
    private String moduleName;
    private double avgGrade;
    private double passRate;
    
    public ModulesReport() {
    };
    
    public ModulesReport(String moduleID) {
        modules = func.readCSV("modules.txt");
        assessmentResult = func.readCSV("assessmentResult.txt");
        this.moduleID = moduleID;
        loadModulesName();
        calculateGrade();
        initComponents();
        loadModuleReport();
    }
    
    private void loadModulesName() {
        moduleName = "";
        for (String[] module : modules) {
            if (module[0].equalsIgnoreCase(moduleID)) {
                moduleName = module[1];
                break;
            }
        }
    }
    
    private void calculateGrade() {
        List<String> studentID = new ArrayList<>();
        List<Double> grades = new ArrayList<>();
    
        // 1. Find all students who took this module
        for (String[] entry : assessmentResult) {
            if (entry[1].equalsIgnoreCase(moduleID) && !studentID.contains(entry[0])) {
                studentID.add(entry[0]);
            }
        }
        // 2. Calculate final grade for each student
        for (String studentid : studentID) {
            double sumGrades = 0;
            int assessmentCount = 0;

            for (String[] entry : assessmentResult) {
                if (entry[0].equals(studentid) && entry[1].equalsIgnoreCase(moduleID)) {
                    sumGrades += Double.parseDouble(entry[3]); // grade column
                    assessmentCount++;
                }
            }

            if (assessmentCount > 0) {
                double Grade = sumGrades / assessmentCount;
                grades.add(Grade);
            }
        }
        
        // 3. Calculate module average
        double sum = 0;
        for (double grade : grades) {
            sum += grade;
        }
        avgGrade = grades.size() > 0 ? sum / grades.size() : 0;

        // 4. Calculate module pass rate (pass mark = 50)
        int passCount = 0;
        for (double grade : grades) {
            if (grade >= 50) passCount++;
        }
        passRate = grades.size() > 0 ? ((double) passCount / grades.size()) * 100 : 0;
    }
    
    private void loadModuleReport() {
        moduleidtxt.setText(moduleID);
        modulenametxt.setText(moduleName);
        averagegradetxt.setText(String.format("%.2f", avgGrade));
        passratetxt.setText(String.format("%.1f%%", passRate));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        moduleidlbl = new javax.swing.JLabel();
        modulenamelbl = new javax.swing.JLabel();
        moduleidtxt = new javax.swing.JTextField();
        modulenametxt = new javax.swing.JTextField();
        averagegradelbl = new javax.swing.JLabel();
        averagegradetxt = new javax.swing.JTextField();
        passratelbl = new javax.swing.JLabel();
        passratetxt = new javax.swing.JTextField();
        numofstudentlbl = new javax.swing.JLabel();
        numberstudenttxt = new javax.swing.JTextField();
        moduleReport = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        moduleidlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        moduleidlbl.setText("Module ID");

        modulenamelbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        modulenamelbl.setText("Module Name");

        moduleidtxt.setEditable(false);

        modulenametxt.setEditable(false);

        averagegradelbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        averagegradelbl.setText("Average Grade");

        averagegradetxt.setEditable(false);

        passratelbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passratelbl.setText("Pass Rate");

        passratetxt.setEditable(false);

        numofstudentlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numofstudentlbl.setText("Number of Student ");

        numberstudenttxt.setEditable(false);

        moduleReport.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        moduleReport.setText("Module Report");

        backbtn.setText("BACK");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(modulenamelbl)
                                .addComponent(moduleidlbl)
                                .addComponent(averagegradelbl)
                                .addComponent(passratelbl)
                                .addComponent(numofstudentlbl))
                            .addGap(56, 56, 56)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(moduleidtxt)
                                .addComponent(modulenametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passratetxt)
                                .addComponent(averagegradetxt)
                                .addComponent(numberstudenttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(115, 115, 115)
                            .addComponent(moduleReport))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(131, 131, 131)
                            .addComponent(backbtn)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(moduleReport)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(moduleidlbl)
                        .addComponent(moduleidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(modulenamelbl)
                        .addComponent(modulenametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numberstudenttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numofstudentlbl))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(averagegradelbl)
                        .addComponent(averagegradetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(passratelbl)
                        .addComponent(passratetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27)
                    .addComponent(backbtn)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        AcadLeadReport acadleadreport = new AcadLeadReport();
        this.setVisible(false);
        acadleadreport.setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ModulesReport().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel averagegradelbl;
    private javax.swing.JTextField averagegradetxt;
    private javax.swing.JButton backbtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel moduleReport;
    private javax.swing.JLabel moduleidlbl;
    private javax.swing.JTextField moduleidtxt;
    private javax.swing.JLabel modulenamelbl;
    private javax.swing.JTextField modulenametxt;
    private javax.swing.JTextField numberstudenttxt;
    private javax.swing.JLabel numofstudentlbl;
    private javax.swing.JLabel passratelbl;
    private javax.swing.JTextField passratetxt;
    // End of variables declaration//GEN-END:variables
}
